server:
  port: 8099

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://goottjason.cafe24.com:3306/goottjason?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: goottjason
    password: mimi1570!!@
  data:
    web:
      pageable:
        max-page-size: 10000  # 기본 2000개 제한을 10000개로 시원하게 늘려줍니다!
  jpa:
    hibernate:
      # 개발 초기엔 update (자동으로 테이블 생성/수정)
      # 운영 시에는 validate 또는 none으로 변경해야 함
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # 로그에 SQL 예쁘게 출력
        show_sql: false   # SQL 실행 로그 보이기
        dialect: org.hibernate.dialect.MariaDBDialect

  # 파일 업로드 용량 제한 해제 (엑셀 파일 업로드용)
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    enabled: true
    path: /docs

cafe24:
  mall-id: "younzara"
  client-id: "r0Z9nXoDDNfOrf5F6wYzTA"
  client-secret: "cr0USvbIP9uiTJ9uh8w7ZB"
  redirect-uri: "https://younzara.cafe24.com/"
  scope: "mall.read_product,mall.write_product"
  token-path: "refresh_token.txt"
coupang:
  api-url: "https://api-gateway.coupang.com"
  vendor-id: "A00213055"
  access-key: "97211801-f495-4fe2-bef3-b614e9d8aaba"
  secret-key: "10523123842c57b7132586c6e55737fc8d08b5c5"
smartstore:
  client-id: "1l5fRuKFzyNJGQF3AP27AE"
  client-secret: "$2a$04$24Vxb0j6X3HK.ZVUA43Wk."
  api-url: "https://api.commerce.naver.com/external"
elevenst:
  api-url: "http://api.11st.co.kr" # 또는 https
  api-key: "b7ac38eb89852b178b17a6a73da0b0c2"

logging:
  file:
    # 프로젝트 최상단에 logs 라는 폴더를 만들고 그 안에 파일로 저장합니다.
    name: logs/market-sync.log
  logback:
    rollingpolicy:
      # 로그 파일이 10MB가 넘어가면 쪼개서 백업합니다.
      max-file-size: 10MB
      # 최대 7일치 로그만 보관하고 옛날 건 지웁니다.
      max-history: 7